image: nixos/nix

before_script:
  # https://github.com/NixOS/nixpkgs/pull/48317
  - ln -s $(nix-build nixpkgs.nix --attr cacert --no-out-link)/etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt

runtime.zip:
  stage: build
  script: nix-shell --run make
  artifacts:
    paths:
    - platform.flatpak
    - sdk.flatpak
